# Generated by Django 4.0.4 on 2022-04-24 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='frist_name',
            new_name='first_name',
        ),
    ]
