# Generated by Django 4.0.4 on 2022-04-28 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='street',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
