# Generated by Django 4.0.4 on 2022-04-19 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0003_category_job_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='slug',
            field=models.SlugField(max_length=40, null=True, unique=True),
        ),
    ]
