# Generated by Django 4.0.4 on 2022-04-19 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0004_job_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='slug',
            field=models.SlugField(blank=True, max_length=40, null=True, unique=True),
        ),
    ]
