# Generated by Django 4.0.4 on 2022-04-23 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0006_apply'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apply',
            old_name='applt_at',
            new_name='apply_at',
        ),
        migrations.RenameField(
            model_name='apply',
            old_name='upload_to',
            new_name='cv',
        ),
    ]
